import os
import psycopg
from psycopg.rows import dict_row

def get_db_connection():
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise RuntimeError("DATABASE_URL is required to connect to Neon PostgreSQL.")
    return psycopg.connect(database_url, row_factory=dict_row)

def init_db():
    conn = get_db_connection()
    try:
        with conn.cursor() as cursor:
            cursor.execute("""
    CREATE TABLE IF NOT EXISTS tasks (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT,
        priority TEXT NOT NULL DEFAULT 'MEDIUM',
        status TEXT NOT NULL DEFAULT 'PENDING',
        deadline TEXT,
        estimated_minutes INTEGER DEFAULT 30,
        actual_minutes INTEGER DEFAULT 0,
        reminder TEXT,
        created_at TEXT,
        updated_at TEXT
    );
    """)

            cursor.execute("""
    CREATE TABLE IF NOT EXISTS subtasks (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        task_id BIGINT NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
        title TEXT NOT NULL,
        completed BOOLEAN NOT NULL DEFAULT FALSE
    );
    """)

        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

if __name__ == "__main__":
    init_db()
    print("Database initialized successfully.")
