import React from 'react';
import RemindersWidget from '../components/RemindersWidget';

export default function RemindersPage({ tasks, onStartTask }) {
  return (
    <div className="space-y-6 max-w-3xl">
      <div>
        <h1 className="text-xl font-bold text-white tracking-tight">Reminders</h1>
        <p className="text-xs text-slate-400">In-app notifications and scheduled reminders generated by AI.</p>
      </div>

      <RemindersWidget tasks={tasks} onStartTask={onStartTask} />
    </div>
  );
}
